const mainTranslation = {
      ru: {
        'site.title':'PADOBI PC — сервис будущего','site.brand':'PADOBI PC','site.tag':'сервис будущего',
        'menu.profile':'Профиль','menu.cart':'Корзина','menu.settings':'Настройки','menu.status':'Статус заказа',
        'hero.title':'Сервис будущего в Киеве','hero.tag':'Твой ПК в надёжных руках — курьер, мастер на дом, гейм-зона и фирменный стиль.',
        'cards.configurator':'Конфигуратор','cards.ready':'Готовые сборки','cards.upgrade':'Апгрейд','cta.build':'Собрать','cta.view':'Смотреть','cta.start':'Начать',
        'why.title':'Почему выбирают нас','why.lead':'Бесплатный курьер по Киеву, мастер на дом и гейм‑зона для клиентов. Минимализм, честность и киберпанк‑атмосфера.',
        'why.courier.title':'Бесплатный курьер','why.courier.text':'Заберём ваш ПК, привезём обратно. Удобно и безопасно.',
        'why.game.title':'Гейм‑зона','why.game.text':'Пока идёт ремонт — сыграйте на консолях и топовых ПК.',
        'why.honest.title':'Честный сервис','why.honest.text':'Прозрачные цены, диагностика и гарантия на все работы 6 месяцев.',
        'services.title':'Наши услуги','services.note':'Цены указаны за работу. Запчасти по согласованию.',
        'srv.clean':'Чистка','srv.clean.desc':'Пыль, профилактика, акустика','srv.paste':'Замена термопасты','srv.paste.desc':'CPU / GPU, правильная посадка',
        'srv.parts':'Замена железа','srv.parts.desc':'RAM / SSD / GPU / PSU','srv.diag':'Диагностика','srv.diag.desc':'Тесты, отчёт, рекомендации','srv.bios':'Прошивка BIOS','srv.bios.desc':'Обновление, восстановление',
        'srv.winpack':'Windows + драйвера + софт','srv.winpack.desc':'Оптимизация, готов к работе','srv.win':'Windows','srv.win.desc':'Установка и настройка','srv.virus':'Чистка вирусов','srv.virus.desc':'Удаление, защита, контроль',
        'about.title':'О нас','about.text':'PADOBI PC — сервисный центр с характером: Мы собираем ПК под задачи, апгрейдим по Trade‑In, настраиваем софт и берём ответственность за результат.',
        'reviews.title':'Отзывы клиентов','reviews.r1':'«Забрали ПК курьером, через день вернули тихим и быстрым. В гейм‑зоне время пролетело незаметно.»','reviews.r2':'«Прозрачные цены и нормальный диалог. Апгрейд и винда — без воды и лишних наворотов.»','reviews.r3':'«Сервис как в будущем: стиль, порядок и уважение к клиенту. Рекомендую.»',
        'faq.title':'FAQ','faq.q1':'Сколько занимает ремонт?','faq.a1':'В среднем 1–2 дня. Точные сроки зависят от задачи и наличия деталей.','faq.q2':'Есть ли гарантия?','faq.a2':'Да. На все работы — 6 месяцев. Условия фиксируем в заказ‑наряде.','faq.q3':'Можно ли вызвать мастера домой?','faq.a3':'Да. Приедет мастер или курьер — как удобнее. По Киеву — бесплатно.',
        'chat.support':'Поддержка','chat.greet':'Здравствуйте! Чем можем помочь?','chat.input':'Введите сообщение...','chat.thanks':'Спасибо за сообщение! Мы скоро ответим.',
        'auth.fill_all':'Заполните все поля','auth.email_invalid':'Введите корректный email','auth.phone_invalid':'Некорректный телефон','auth.pass_short':'Минимум 6 символов','auth.reg_ok':'Регистрация успешна! Подтвердите email.','auth.reg_error':'Ошибка регистрации','auth.login_error':'Ошибка входа',
        'footer_name':'сервис будущего',
      },
      ua: {
        'site.title':'PADOBI PC — сервіс майбутнього','site.brand':'PADOBI PC','site.tag':'сервіс майбутнього',
        'menu.profile':'Профіль','menu.cart':'Кошик','menu.settings':'Налаштування','menu.status':'Статус замовлення',
        'hero.title':'Сервіс майбутнього в Києві','hero.tag':'Твій ПК у надійних руках — кур’єр, майстер додому, гейм-зона та фірмовий стиль.',
        'cards.configurator':'Конфігуратор','cards.ready':'Готові збірки','cards.upgrade':'Апгрейд','cta.build':'Зібрати','cta.view':'Дивитись','cta.start':'Почати',
        'why.title':'Чому обирають нас','why.lead':'Безкоштовний кур’єр по Києву, майстер додому та гейм-зона для клієнтів. Мінімалізм, чесність і кіберпанк-атмосфера.',
        'why.courier.title':'Безкоштовний кур’єр','why.courier.text':'Заберемо ваш ПК і повернемо назад. Зручно та безпечно.',
        'why.game.title':'Гейм-зона','why.game.text':'Поки триває ремонт — зіграйте на консолях і топових ПК.',
        'why.honest.title':'Чесний сервіс','why.honest.text':'Прозорі ціни, діагностика і гарантія 6 місяців.',
        'services.title':'Наші послуги','services.note':'Ціни вказані за роботу. Запчастини за погодженням.',
        'srv.clean':'Чистка','srv.clean.desc':'Пил, профілактика, акустика','srv.paste':'Заміна термопасти','srv.paste.desc':'CPU / GPU, правильна посадка',
        'srv.parts':'Заміна заліза','srv.parts.desc':'RAM / SSD / GPU / PSU','srv.diag':'Діагностика','srv.diag.desc':'Тести, звіт, рекомендації','srv.bios':'Прошивка BIOS','srv.bios.desc':'Оновлення, відновлення',
        'srv.winpack':'Windows + драйвери + софт','srv.winpack.desc':'Оптимізація, готовий до роботи','srv.win':'Windows','srv.win.desc':'Встановлення і налаштування','srv.virus':'Чистка вірусів','srv.virus.desc':'Видалення, захист, контроль',
        'about.title':'Про нас','about.text':'PADOBI PC — сервісний центр з характером: Збираємо ПК під задачі, апгрейд по Trade-In, налаштовуємо софт і відповідаємо за результат.',
        'reviews.title':'Відгуки клієнтів','reviews.r1':'«Забрали ПК кур’єром, за день повернули тихим і швидким. У гейм-зоні час пролетів непомітно.»','reviews.r2':'«Прозорі ціни і нормальний діалог. Апгрейд і вінда — без води.»','reviews.r3':'«Сервіс як у майбутньому: стиль і повага до клієнта. Рекомендую.»',
        'faq.title':'FAQ','faq.q1':'Скільки триває ремонт?','faq.a1':'В середньому 1–2 дні. Залежить від задачі та наявності деталей.','faq.q2':'Чи є гарантія?','faq.a2':'Так. На всі роботи — 6 місяців. Умови фіксуємо в замовленні.','faq.q3':'Чи можна викликати майстра додому?','faq.a3':'Так. Приїде майстер або кур’єр — як зручніше. По Києву — безкоштовно.',
        'chat.support':'Підтримка','chat.greet':'Вітаємо! Як можемо допомогти?','chat.input':'Введіть повідомлення...','chat.thanks':'Дякуємо за повідомлення! Ми скоро відповімо.',
        'auth.login':'Вхід','auth.register':'Реєстрація','auth.email':'Email','auth.password':'Пароль','auth.username':'Ім’я користувача','auth.phone':'Номер телефону',
        'auth.fill_all':'Заповніть всі поля','auth.email_invalid':'Введіть коректний email','auth.phone_invalid':'Некоректний телефон','auth.pass_short':'Мінімум 6 символів у паролі','auth.reg_ok':'Реєстрація успішна! Підтвердьте email.','auth.reg_error':'Помилка реєстрації','auth.login_error':'Помилка входу',
        'footer_name':'сервис будущего',

      },
      en: {
        'site.title':'PADOBI PC — Future Service','site.brand':'PADOBI PC','site.tag':'future service',
        'menu.profile':'Profile','menu.cart':'Cart','menu.settings':'Settings','menu.status':'Order Status',
        'hero.title':'Future‑proof PC Service in Kyiv','hero.tag':'Your PC in safe hands — courier, home service, game zone and signature style.',
        'cards.configurator':'Configurator','cards.ready':'Prebuilt PCs','cards.upgrade':'Upgrade','cta.build':'Build','cta.view':'Browse','cta.start':'Start',
        'why.title':'Why choose us','why.lead':'Free courier in Kyiv, on‑site technician and a client‑only game zone. Minimalism, honesty and cyberpunk vibes.',
        'why.courier.title':'Free courier','why.courier.text':'We pick up and return your PC. Convenient and safe.',
        'why.game.title':'Game zone','why.game.text':'While we do quick fixes — enjoy consoles or high‑end PCs.',
        'why.honest.title':'Honest service','why.honest.text':'Transparent pricing, diagnostics and up 6 warranty.',
        'services.title':'Our services','services.note':'Labour only. Parts by agreement.',
        'srv.clean':'Cleaning','srv.clean.desc':'Dust, prevention, acoustics','srv.paste':'Thermal paste','srv.paste.desc':'CPU / GPU, proper mount',
        'srv.parts':'Hardware replacement','srv.parts.desc':'RAM / SSD / GPU / PSU','srv.diag':'Diagnostics','srv.diag.desc':'Stress tests, report, advice','srv.bios':'BIOS flashing','srv.bios.desc':'Update, recovery',
        'srv.winpack':'Windows + drivers + apps','srv.winpack.desc':'Optimized, ready to work','srv.win':'Windows','srv.win.desc':'Install & setup','srv.virus':'Virus cleanup','srv.virus.desc':'Removal, protection, control',
        'about.title':'About us','about.text':'PADOBI PC — a service center with attitude: respect for client time. We build PCs for tasks, upgrade via Trade‑In, configure software and own the result.',
        'reviews.title':'Reviews','reviews.r1':'“Courier pickup, next‑day return — quiet and fast. Game zone made the wait fly.”','reviews.r2':'“Transparent pricing and straight talk. Upgrade + Windows done right.”','reviews.r3':'“Feels like the future: style, order and respect. Recommend.”',
        'faq.title':'FAQ','faq.q1':'How long does repair take?','faq.a1':'Usually 1–2 days depending on task and parts availability.','faq.q2':'Is there a warranty?','faq.a2':'Yes, up 6 on labour. Details in the work order.','faq.q3':'Can a tech come to my place?','faq.a3':'Yes. Technician or courier — your choice. Free in Kyiv.',
        'chat.support':'Support','chat.greet':'Hello! How can we help you?','chat.input':'Type a message...','chat.thanks':'Thank you! We will reply soon.',
        'auth.login':'Login','auth.register':'Register','auth.email':'Email','auth.password':'Password','auth.username':'Username','auth.phone':'Phone',
        'auth.fill_all':'Fill all fields','auth.email_invalid':'Enter valid email','auth.phone_invalid':'Invalid phone','auth.pass_short':'Minimum 6 characters','auth.reg_ok':'Registration success! Confirm your email.','auth.reg_error':'Registration error','auth.login_error':'Login error',
        'footer_name':'сервис будущего',
      }
    };
const configureTranlation = {
    ua: {
    "page.title": "Конфігуратор ПК",
    "page.lead": "Збирайте збірку, перевіряйте сумісність і додавайте до кошика.",
    "page.hint_short": "Почніть з CPU або GPU",
    "section.configurator": "Конфігуратор",
    "cpu.title": "Процесор (CPU)",
    "cpu.desc": "Виберіть процесор — сокет та TDP вказані в опціях.",
    "opt.cpu.intel_i5_14600": "Intel i5-14600 — 8 500 ₴ — LGA1700 — 65W",
    "opt.cpu.intel_i7_14700": "Intel i7-14700 — 14 500 ₴ — LGA1700 — 125W",
    "opt.cpu.ryzen_7_7800x": "Ryzen 7 7800X — 11 000 ₴ — AM5 — 105W",
    "mb.title": "Материнська плата (MB)",
    "mb.desc": "Обирайте плату з сумісним сокетом та потрібним форм-фактором.",
    "opt.mb.asus_tuf": "ASUS TUF (LGA1700, ATX) — 5 600 ₴",
    "opt.mb.msi_mag": "MSI MAG (AM5, ATX) — 6 200 ₴",
    "opt.mb.gigabyte_b660m": "Gigabyte B660M (mATX) — 4 200 ₴",
    "gpu.title": "Відеокарта (GPU)",
    "gpu.desc": "Вкажіть довжину в мм та TDP (потрібно для перевірки корпусу та живлення).",
    "opt.gpu.rtx_4070_ti": "RTX 4070 Ti — 25 000 ₴ — 285мм — 285W",
    "opt.gpu.rtx_4090": "RTX 4090 — 42 000 ₴ — 336мм — 450W",
    "opt.gpu.rx_7800_xt": "RX 7800 XT — 16 000 ₴ — 300мм — 300W",
    "cooler.title": "Кулер (CPU Cooler)",
    "cooler.desc": "Висота кулера важлива для сумісності з корпусом.",
    "opt.cooler.air_160": "Air Cooler — 1 400 ₴ — 160мм",
    "opt.cooler.aio_240": "AIO 240мм — 3 600 ₴ — low-profile",
    "opt.cooler.air_180": "Air Cooler — 2 200 ₴ — 180мм",
    "ram.title": "Оперативна пам’ять (RAM)",
    "ram.desc": "DDR5 рекомендуємо для сучасних систем.",
    "opt.ram.16gb": "16 GB DDR5 — 2 200 ₴",
    "opt.ram.32gb": "32 GB DDR5 — 4 200 ₴",
    "opt.ram.64gb": "64 GB DDR5 — 8 200 ₴",
    "storage.title": "Накопичувач (SSD)",
    "storage.desc": "NVMe для системи — збільшить швидкість завантаження.",
    "opt.storage.500gb": "500 GB NVMe — 2 400 ₴",
    "opt.storage.1tb": "1 TB NVMe — 4 200 ₴",
    "opt.storage.2tb": "2 TB NVMe — 7 600 ₴",
    "psu.title": "Блок живлення (PSU)",
    "psu.desc": "Обирайте з запасом потужності — ми рахуємо необхідні Вт по компонентах.",
    "opt.psu.650w": "650 W Gold — 2 600 ₴",
    "opt.psu.850w": "850 W Gold — 3 600 ₴",
    "opt.psu.1200w": "1200 W Platinum — 5 200 ₴",
    "case.title": "Корпус",
    "case.desc": "Перевірте підтримувану довжину відеокарти та висоту кулера.",
    "opt.case.mid_tower": "Mid Tower ARGB — 3 200 ₴ — max GPU 350мм",
    "opt.case.compact": "Compact ATX — 2 400 ₴ — max GPU 300мм",
    "opt.case.full_tower": "Full Tower — 4 800 ₴ — max GPU 400мм",
    "compat.hint": "Поради щодо сумісності та потужності з’являться тут.",
    "summary.title": "Збірка — коротка зведення",
    "summary.total_label": "До оплати",
    "compat.messages": "Тут будуть повідомлення про сумісність",
    "buttons.save": "Зберегти збірку",
    "buttons.add_cart": "Додати до кошика",
    "buttons.reset": "Скинути",
    "presets.title": "Попередньо встановлені збірки",
    "saved.title": "Збережені збірки"
  },
  ru: {
    "page.title": "Конфигуратор ПК",
    "page.lead": "Собирайте сборку, проверяйте совместимость и добавляйте в корзину.",
    "page.hint_short": "Начните с CPU или GPU",
    "section.configurator": "Конфигуратор",
    "cpu.title": "Процессор (CPU)",
    "cpu.desc": "Выберите процессор — сокет и TDP указаны в опциях.",
    "opt.cpu.intel_i5_14600": "Intel i5-14600 — 8 500 ₴ — LGA1700 — 65W",
    "opt.cpu.intel_i7_14700": "Intel i7-14700 — 14 500 ₴ — LGA1700 — 125W",
    "opt.cpu.ryzen_7_7800x": "Ryzen 7 7800X — 11 000 ₴ — AM5 — 105W",
    "mb.title": "Материнская плата (MB)",
    "mb.desc": "Выбирайте плату с совместимым сокетом и нужным форм-фактором.",
    "opt.mb.asus_tuf": "ASUS TUF (LGA1700, ATX) — 5 600 ₴",
    "opt.mb.msi_mag": "MSI MAG (AM5, ATX) — 6 200 ₴",
    "opt.mb.gigabyte_b660m": "Gigabyte B660M (mATX) — 4 200 ₴",
    "gpu.title": "Видеокарта (GPU)",
    "gpu.desc": "Укажите длину в мм и TDP (нужно для проверки корпуса и питания).",
    "opt.gpu.rtx_4070_ti": "RTX 4070 Ti — 25 000 ₴ — 285мм — 285W",
    "opt.gpu.rtx_4090": "RTX 4090 — 42 000 ₴ — 336мм — 450W",
    "opt.gpu.rx_7800_xt": "RX 7800 XT — 16 000 ₴ — 300мм — 300W",
    "cooler.title": "Кулер (CPU Cooler)",
    "cooler.desc": "Высота кулера важна для совместимости с корпусом.",
    "opt.cooler.air_160": "Air Cooler — 1 400 ₴ — 160мм",
    "opt.cooler.aio_240": "AIO 240мм — 3 600 ₴ — low-profile",
    "opt.cooler.air_180": "Air Cooler — 2 200 ₴ — 180мм",
    "ram.title": "Оперативная память (RAM)",
    "ram.desc": "DDR5 рекомендуем для современных систем.",
    "opt.ram.16gb": "16 GB DDR5 — 2 200 ₴",
    "opt.ram.32gb": "32 GB DDR5 — 4 200 ₴",
    "opt.ram.64gb": "64 GB DDR5 — 8 200 ₴",
    "storage.title": "Накопитель (SSD)",
    "storage.desc": "NVMe для системы — увеличит скорость загрузки.",
    "opt.storage.500gb": "500 GB NVMe — 2 400 ₴",
    "opt.storage.1tb": "1 TB NVMe — 4 200 ₴",
    "opt.storage.2tb": "2 TB NVMe — 7 600 ₴",
    "psu.title": "Блок питания (PSU)",
    "psu.desc": "Выберите с запасом мощности — мы считаем необходимые Вт по компонентам.",
    "opt.psu.650w": "650 W Gold — 2 600 ₴",
    "opt.psu.850w": "850 W Gold — 3 600 ₴",
    "opt.psu.1200w": "1200 W Platinum — 5 200 ₴",
    "case.title": "Корпус",
    "case.desc": "Проверьте поддерживаемую длину видеокарты и высоту кулера.",
    "opt.case.mid_tower": "Mid Tower ARGB — 3 200 ₴ — max GPU 350мм",
    "opt.case.compact": "Compact ATX — 2 400 ₴ — max GPU 300мм",
    "opt.case.full_tower": "Full Tower — 4 800 ₴ — max GPU 400мм",
    "compat.hint": "Советы по совместимости и мощности появятся здесь.",
    "summary.title": "Сборка — краткая сводка",
    "summary.total_label": "К оплате",
    "compat.messages": "Здесь будут сообщения о совместимости",
    "buttons.save": "Сохранить сборку",
    "buttons.add_cart": "Добавить в корзину",
    "buttons.reset": "Сбросить",
    "presets.title": "Предустановки",
    "saved.title": "Сохранённые сборки"
  },
  en: {
    "page.title": "PC Configurator",
    "page.lead": "Build your PC, check compatibility, and add to cart.",
    "page.hint_short": "Start with CPU or GPU",
    "section.configurator": "Configurator",
    "cpu.title": "Processor (CPU)",
    "cpu.desc": "Select a processor — socket and TDP are listed in options.",
    "opt.cpu.intel_i5_14600": "Intel i5-14600 — 8,500 ₴ — LGA1700 — 65W",
    "opt.cpu.intel_i7_14700": "Intel i7-14700 — 14,500 ₴ — LGA1700 — 125W",
    "opt.cpu.ryzen_7_7800x": "Ryzen 7 7800X — 11,000 ₴ — AM5 — 105W",
    "mb.title": "Motherboard (MB)",
    "mb.desc": "Choose a board with a compatible socket and required form factor.",
    "opt.mb.asus_tuf": "ASUS TUF (LGA1700, ATX) — 5,600 ₴",
    "opt.mb.msi_mag": "MSI MAG (AM5, ATX) — 6,200 ₴",
    "opt.mb.gigabyte_b660m": "Gigabyte B660M (mATX) — 4,200 ₴",
    "gpu.title": "Graphics Card (GPU)",
    "gpu.desc": "Specify length in mm and TDP (needed for case and power check).",
    "opt.gpu.rtx_4070_ti": "RTX 4070 Ti — 25,000 ₴ — 285mm — 285W",
    "opt.gpu.rtx_4090": "RTX 4090 — 42,000 ₴ — 336mm — 450W",
    "opt.gpu.rx_7800_xt": "RX 7800 XT — 16,000 ₴ — 300mm — 300W",
    "cooler.title": "Cooler (CPU Cooler)",
    "cooler.desc": "Cooler height matters for case compatibility.",
    "opt.cooler.air_160": "Air Cooler — 1,400 ₴ — 160mm",
    "opt.cooler.aio_240": "AIO 240mm — 3,600 ₴ — low-profile",
    "opt.cooler.air_180": "Air Cooler — 2,200 ₴ — 180mm",
    "ram.title": "RAM",
    "ram.desc": "DDR5 recommended for modern systems.",
    "opt.ram.16gb": "16 GB DDR5 — 2,200 ₴",
    "opt.ram.32gb": "32 GB DDR5 — 4,200 ₴",
    "opt.ram.64gb": "64 GB DDR5 — 8,200 ₴",
    "storage.title": "Storage (SSD)",
    "storage.desc": "NVMe for system — increases loading speed.",
    "opt.storage.500gb": "500 GB NVMe — 2,400 ₴",
    "opt.storage.1tb": "1 TB NVMe — 4,200 ₴",
    "opt.storage.2tb": "2 TB NVMe — 7,600 ₴",
    "psu.title": "Power Supply (PSU)",
    "psu.desc": "Choose with headroom — we calculate required W by components.",
    "opt.psu.650w": "650 W Gold — 2,600 ₴",
    "opt.psu.850w": "850 W Gold — 3,600 ₴",
    "opt.psu.1200w": "1200 W Platinum — 5,200 ₴",
    "case.title": "Case",
    "case.desc": "Check supported GPU length and cooler height.",
    "opt.case.mid_tower": "Mid Tower ARGB — 3,200 ₴ — max GPU 350mm",
    "opt.case.compact": "Compact ATX — 2,400 ₴ — max GPU 300mm",
    "opt.case.full_tower": "Full Tower — 4,800 ₴ — max GPU 400mm",
    "compat.hint": "Compatibility and power tips will appear here.",
    "summary.title": "Build — summary",
    "summary.total_label": "Total",
    "compat.messages": "Compatibility messages will appear here",
    "buttons.save": "Save Build",
    "buttons.add_cart": "Add to Cart",
    "buttons.reset": "Reset",
    "presets.title": "Presets",
    "saved.title": "Saved Builds"
  }
};
const prebuildTranslation = {
    ua: {
    "builds.title": "Готові збірки",
    "builds.lead": "Підберіть збірку за бюджетом і завданнями — все протестовано та готово до використання.",
    "builds.filter_category": "Фільтр за категорією",
    "builds.sort": "Сортування",
    "builds.search": "Пошук за назвою...",
    "builds.open_configurator": "Відкрити конфігуратор",
    "support.title": "Підтримка",
    "support.text": "Потрібна консультація щодо збірки? Допоможемо обрати модель під завдання.",
    "support.email": "info@padobipc.com",
    "favorites.title": "Вибране",
    "favorites.empty": "Поки порожньо"
  },
  ru: {
    "builds.title": "Готовые сборки",
    "builds.lead": "Подберите сборку по бюджету и задачам — всё протестировано и готово к использованию.",
    "builds.filter_category": "Фильтр по категории",
    "builds.sort": "Сортировка",
    "builds.search": "Поиск по названию...",
    "builds.open_configurator": "Открыть конфигуратор",
    "support.title": "Поддержка",
    "support.text": "Нужна консультация по сборке? Поможем выбрать модель под задачу.",
    "support.email": "info@padobipc.com",
    "favorites.title": "Избранное",
    "favorites.empty": "Пока пусто"
  },
  en: {
    "builds.title": "Ready Builds",
    "builds.lead": "Select a build by budget and tasks — everything tested and ready to use.",
    "builds.filter_category": "Filter by category",
    "builds.sort": "Sort",
    "builds.search": "Search by name...",
    "builds.open_configurator": "Open Configurator",
    "support.title": "Support",
    "support.text": "Need help choosing a build? We'll help you select a model for your task.",
    "support.email": "info@padobipc.com",
    "favorites.title": "Favorites",
    "favorites.empty": "Empty for now"
  }
};
const upgradeTranslation = {
    ua: {
    "tradein.title": "Апгрейд і Trade‑in",
    "tradein.lead": "Здавайте свої старі комплектуючі — отримайте зарахування при покупці нового. Попередня оцінка доступна онлайн; остаточна — у майстерні після тестування.",
    "tradein.step1": "1. Що ви здаєте",
    "tradein.step2": "2. Що хочете взяти",
    "tradein.step3": "3. Оформлення",
    "tradein.label_name": "ПІБ / Назва",
    "tradein.label_phone": "Телефон",
    "tradein.label_parts": "Список комплектуючих (здаєте)",
    "tradein.new_part_type": "Тип компонента",
    "tradein.add_part": "Додати",
    "tradein.add_part_hint": "Вкажіть модель і стан — ми оцінемо.",
    "tradein.label_photos": "Фото компонентів (опційно)",
    "tradein.label_target": "Цільовий апгрейд",
    "tradein.label_note": "Дод. нотатки",
    "tradein.label_agree": "Умови та підтвердження",
    "tradein.label_agree_text": "Я ознайомився з умовами trade‑in і погоджуюсь на оцінку стану",
    "tradein.estimate": "Оцінити зараз",
    "tradein.save_quote": "Зберегти запит",
    "tradein.summary_title": "Зведення оцінки"
  },
  ru: {
    "tradein.title": "Апгрейд и Trade‑in",
    "tradein.lead": "Сдавайте свои старые комплектующие — получите зачёт при покупке нового. Предварительная оценка доступна онлайн; окончательная — в мастерской после тестирования.",
    "tradein.step1": "1. Что вы сдаёте",
    "tradein.step2": "2. Что хотите взять",
    "tradein.step3": "3. Оформление",
    "tradein.label_name": "ФИО / Название",
    "tradein.label_phone": "Телефон",
    "tradein.label_parts": "Список комплектующих (сдаёте)",
    "tradein.new_part_type": "Тип компонента",
    "tradein.add_part": "Добавить",
    "tradein.add_part_hint": "Укажите модель и состояние — мы оценим.",
    "tradein.label_photos": "Фото компонентов (опционально)",
    "tradein.label_target": "Целевой апгрейд",
    "tradein.label_note": "Доп. заметки",
    "tradein.label_agree": "Условия и подтверждение",
    "tradein.label_agree_text": "Я ознакомился с условиями trade‑in и согласен на оценку состояния",
    "tradein.estimate": "Оценить сейчас",
    "tradein.save_quote": "Сохранить запрос",
    "tradein.summary_title": "Сводка оценки"
  },
  en: {
    "tradein.title": "Upgrade and Trade‑in",
    "tradein.lead": "Submit your old components — get credit towards a new purchase. Preliminary evaluation available online; final — at the workshop after testing.",
    "tradein.step1": "1. What you are giving",
    "tradein.step2": "2. What you want to take",
    "tradein.step3": "3. Checkout",
    "tradein.label_name": "Full Name / Company",
    "tradein.label_phone": "Phone",
    "tradein.label_parts": "Components list (you submit)",
    "tradein.new_part_type": "Component type",
    "tradein.add_part": "Add",
    "tradein.add_part_hint": "Specify model and condition — we will evaluate.",
    "tradein.label_photos": "Component photos (optional)",
    "tradein.label_target": "Target upgrade",
    "tradein.label_note": "Additional notes",
    "tradein.label_agree": "Terms and confirmation",
    "tradein.label_agree_text": "I have read the trade‑in terms and agree to the condition evaluation",
    "tradein.estimate": "Estimate now",
    "tradein.save_quote": "Save request",
    "tradein.summary_title": "Evaluation Summary"
  }
};

const pageToTrans = {
    '/': mainTranslation,
    'configurator': configureTranlation,
    'prebuild': prebuildTranslation,
    'upgrade': upgradeTranslation,
};

function getCurrentPageName(){
    const name = location.pathname.split("/").pop();
    return name;
};

export default function setLangOfPage(){
    const namePage = getCurrentPageName();
    console.log(namePage)
    if(pageToTrans[namePage] == undefined)return pageToTrans['/'];
    return pageToTrans[namePage];
};
